image:
  file: .gitpod.Dockerfile

tasks:
  - name: Initialize Environment
    init: |
      # Start PostgreSQL
      sudo service postgresql start
      # Create and activate Python virtual environment
      python3 -m venv venv
      source venv/bin/activate
      # Install Python dependencies
      pip install --upgrade pip
      pip install -r requirements.txt
      # Add any other initialization commands here

  - name: Development Server
    command: |
      source venv/bin/activate
      python manage.py runserver 0.0.0.0:8000
    openMode: tab-after

  - name: Uptime Monitor (Optional)
    command: . ${GITPOD_REPO_ROOT}/.vscode/uptime.sh &
    openMode: split-right

vscode:
  extensions:
    # Python/Jupyter
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    
    # Web Development
    - formulahendry.auto-close-tag
    - eventyret.bootstrap-4-cdn-snippet
    - hookyqr.beautify
    
    # Utilities
    - matt-rudge.auto-open-preview-panel
    - dbaeumer.vscode-eslint