# Generated by Django 3.2.25 on 2026-03-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_id_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='critical_stock_threshold',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_rules',
            field=models.JSONField(blank=True, default=list, help_text='Optional list like [{"minimum_quantity": 5, "discount_rate": 0.05}]'),
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=25),
        ),
    ]
