# Generated by Django 3.2.25 on 2026-03-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20260309_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='critical_stock_threshold',
            field=models.PositiveIntegerField(blank=True, default=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(blank=True, default=25),
        ),
    ]
